package spn.node.type;

import spn.language.SpnTypeName;
import com.oracle.truffle.api.dsl.Fallback;
import com.oracle.truffle.api.dsl.NodeChild;
import com.oracle.truffle.api.dsl.Specialization;
import com.oracle.truffle.api.nodes.NodeInfo;
import spn.language.SpnException;
import spn.node.SpnExpressionNode;
import spn.type.SpnConstrainedValue;

/**
 * Extracts the raw value from a SpnConstrainedValue so that normal arithmetic
 * nodes (SpnAddNode, etc.) can operate on it without knowing about constrained types.
 *
 * KEY TRUFFLE CONCEPT: Type-specialized unwrapping
 *
 * The inner value could be Long, Double, Boolean, etc. We specialize on the inner
 * type so that the parent node can use the fast typed execution path:
 *
 *   SpnAddNode calls executeLong() on its children
 *     → SpnUnwrapConstrainedNode.executeLong() (generated by DSL)
 *       → hits unwrapLong specialization → returns raw long, no boxing
 *
 * The guards check the inner value's type. Since the inner type is usually stable
 * (a Natural always holds a Long), the guard becomes a no-op after compilation.
 *
 * Usage in AST composition:
 * <pre>
 *   // For:  x + y  where both are Natural
 *   var readX = SpnReadLocalVariableNodeGen.create(xSlot);
 *   var readY = SpnReadLocalVariableNodeGen.create(ySlot);
 *   var unwrapX = SpnUnwrapConstrainedNodeGen.create(readX);
 *   var unwrapY = SpnUnwrapConstrainedNodeGen.create(readY);
 *   var add = SpnAddNodeGen.create(unwrapX, unwrapY);
 *   var checked = new SpnCheckConstraintNode(add, naturalType);
 * </pre>
 */
@NodeChild("value")
@NodeInfo(shortName = "unwrap")
public abstract class SpnUnwrapConstrainedNode extends SpnExpressionNode {

    protected static boolean isLong(SpnConstrainedValue v) {
        return v.getValue() instanceof Long;
    }

    protected static boolean isDouble(SpnConstrainedValue v) {
        return v.getValue() instanceof Double;
    }

    protected static boolean isBoolean(SpnConstrainedValue v) {
        return v.getValue() instanceof Boolean;
    }

    @Specialization(guards = "isLong(constrained)")
    protected long unwrapLong(SpnConstrainedValue constrained) {
        return (long) constrained.getValue();
    }

    @Specialization(guards = "isDouble(constrained)")
    protected double unwrapDouble(SpnConstrainedValue constrained) {
        return (double) constrained.getValue();
    }

    @Specialization(guards = "isBoolean(constrained)")
    protected boolean unwrapBoolean(SpnConstrainedValue constrained) {
        return (boolean) constrained.getValue();
    }

    @Specialization(replaces = {"unwrapLong", "unwrapDouble", "unwrapBoolean"})
    protected Object unwrapGeneric(SpnConstrainedValue constrained) {
        return constrained.getValue();
    }

    @Fallback
    protected Object notConstrained(Object value) {
        throw new SpnException("Expected a constrained value, got: "
                + SpnTypeName.of(value), this);
    }
}
