package spn.node;

import com.oracle.truffle.api.frame.VirtualFrame;
import com.oracle.truffle.api.nodes.UnexpectedResultException;
import spn.type.SpnTypesGen;

/**
 * Base class for all SPN expression nodes.
 *
 * Expressions evaluate to a value. This class extends SpnStatementNode so that
 * any expression can appear where a statement is expected (the value is discarded).
 *
 * KEY TRUFFLE CONCEPT: Typed execute methods and type specialization
 *
 * The generic path is executeGeneric() which returns a boxed Object. But boxing
 * primitives (long -> Long) kills performance. So we provide typed execute methods:
 *
 *   executeLong(frame)     -- returns a raw long, no boxing
 *   executeDouble(frame)   -- returns a raw double, no boxing
 *   executeBoolean(frame)  -- returns a raw boolean, no boxing
 *
 * When a parent node (like SpnAddNode) knows its child is producing a long, it calls
 * executeLong() directly, avoiding boxing entirely. If the child unexpectedly produces
 * a different type, it throws UnexpectedResultException, which triggers the parent to
 * deoptimize and respecialize for the new type. This is the core of Truffle's
 * "speculate and deoptimize" strategy.
 *
 * The SpnTypesGen class is auto-generated by the Truffle DSL processor from our
 * @TypeSystem annotation. It provides expectLong(), expectDouble(), etc.
 */
public abstract class SpnExpressionNode extends SpnStatementNode {

    /**
     * The generic execution method. Every expression must implement this.
     * Returns a boxed Object -- the "slow path" that always works.
     */
    public abstract Object executeGeneric(VirtualFrame frame);

    /**
     * When used as a statement, just execute and discard the result.
     */
    @Override
    public void executeVoid(VirtualFrame frame) {
        executeGeneric(frame);
    }

    /**
     * Fast path for long values. Avoids boxing when the parent knows (or speculates)
     * that this expression produces a long.
     */
    public long executeLong(VirtualFrame frame) throws UnexpectedResultException {
        return SpnTypesGen.expectLong(executeGeneric(frame));
    }

    /**
     * Fast path for double values.
     */
    public double executeDouble(VirtualFrame frame) throws UnexpectedResultException {
        return SpnTypesGen.expectDouble(executeGeneric(frame));
    }

    /**
     * Fast path for boolean values.
     */
    public boolean executeBoolean(VirtualFrame frame) throws UnexpectedResultException {
        return SpnTypesGen.expectBoolean(executeGeneric(frame));
    }
}
